server:
  port: 8080
#spring环境配置
spring:
  #连接数据库的配置
  datasource:
    #连接数据库的驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
    #连接数据库的驱地址
    url: jdbc:mysql://localhost:3306/homestay?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    #连接数据库的用户名和密码
    username: root
    password: root

    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    # 扩展插件
    # 监控统计用的filter:stat 日志用的filter:log4j 防御sql注入的filter:wall
#    filters: stat
    # 最大连接池数量
    maxActive: 20
    # 初始化时建立物理连接的个数。初始化发生在显示调用init方法，或者第一次getConnection时
    initialSize: 1
    # 获取连接时最大等待时间，单位毫秒
    maxWait: 60000
    # 最小连接池数量
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    # 连接保持空闲而不被驱逐的最长时间
    minEvictableIdleTimeMillis: 300000
    # 用来检测连接是否有效的sql，要求是一个查询语句
    # 如果validationQuery为null，testOnBorrow、testOnReturn、testWhileIdle都不会其作用
    validationQuery: select count(1) from 'table'
    # 申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效
    testWhileIdle: true
    # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
    testOnBorrow: false
    # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
    testOnReturn: false
    # 是否缓存preparedStatement，即PSCache
    poolPreparedStatements: false
    # 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true
    maxOpenPreparedStatements: -1
#  redis:
#    database: 1
#    host: 127.0.0.1
#    port: 6379
#    password:
#    timeout: 6000
#    pool:
#      max-active: 1000
#      max-wait: -1
#      max-idle: 10
#      min-idle: 5

  #thmeleaf的配置
  thymeleaf:
    #thmeleaf使用HTML5的标准
    mode: HTML5
    #thmeleaf的编码
    encoding: UTF-8
    #thmeleaf 热部署 不需要重启服务器，在页面上刷新即可渲染 cache: 是否缓存，开发模式下设置为false，避免改了模板还要重启服务器，线上设置为true，可以提高性能。
    cache: false
#    servlet:
#      content-type: text/html
#    prefix:
#      classpath: classpath:/templates/  #prefix：指定模板所在的目录
#    check-template-location: true  #check-tempate-location: 检查模板路径是否存在
#    suffix: .html
#    enabled: true
  #thmeleafend
#pring end

# pagehelper分页插件
pagehelper:
  # 数据库的方言
  helperDialect: mysql
  # 启用合理化，如果pageNum < 1会查询第一页，如果pageNum > pages会查询最后一页
  reasonable: true
#配置mybatis
mybatis:
  # mapper.xml包地址
  mapper-locations: classpath:mapper/*.xml
  # pojo生成包地址
  type-aliases-package: com.bsuc.homestay.entity

#配置 日志
#logging：
#  config：classpath:log/logback.xml
#  path: E:\Homestay\homestay-log
logging:
  level:
    root: info
  path: ./logs
homestay:
  allowedOrigins: http://localhost:63343

#mybatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      logic-delete-field: flag  #全局逻辑删除字段值