#spring环境配置
spring:
  #连接数据库的配置
  datasource:
    #连接数据库的驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
    #连接数据库的驱地址
    url: jdbc:mysql://localhost:3306/homestay?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    #连接数据库的用户名和密码
    username: root
    password: root

  #thmeleaf的配置
  thymeleaf:
    #thmeleaf使用HTML5的标准
    mode: HTML5
    #thmeleaf的编码
    encoding: UTF-8
    #thmeleaf 热部署 不需要重启服务器，在页面上刷新即可渲染 cache: 是否缓存，开发模式下设置为false，避免改了模板还要重启服务器，线上设置为true，可以提高性能。
    cache: false
#    servlet:
#      content-type: text/html
#    prefix:
#      classpath: classpath:/templates/  #prefix：指定模板所在的目录
#    check-template-location: true  #check-tempate-location: 检查模板路径是否存在
#    suffix: .html
#    enabled: true